version: '3.7'
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
    - '9000:9000'
    networks:
    - pet_host
    labels:
    - "traefik.enable=false"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainerdata:/data

  traefik:
    image: traefik:latest # The official Traefik docker image
    container_name: traefik
    command: --docker --api --docker.watch --docker.domain=docker.localhost --logLevel=DEBUG  --docker.endpoint=tcp://socat:2375 --docker.exposedbydefault=false # Enables the web UI and tells Træfik to listen to docker, without exposing by default
    networks:
    - internal
    - pet_host
    ports:
    - "80:80"     # The HTTP port
    - "8080:8080" # The Web UI (enabled by --api)
    - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    - /root/traefik.toml:/traefik.toml
    - /root/acme.json:/acme.json

  mysql:
    image: mysql:latest
    container_name: db
    volumes:
    - ./db:/usr/src/pet_gateway
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=pet_host"
    environment:
    - MYSQL_DATABASE_PORT
    - MYSQL_ROOT_PASSWORD=1234567890
    - MYSQL_DATABASE=database
    networks:
    - internal

  socat:
    image: alpine/socat
    container_name: socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - internal

  pet_gateway:
    build: "./pet_gateway/"
    container_name: pet_gateway
    command: -t -i --device=/dev/bus/usb/003/017 ubuntu bash
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    networks:
    - pet_host
    volumes:
    - ./server/src:/usr/src/pet_gateway/src
    - db:/usr/src/pet_gateway
    entrypoint:
    - /usr/local/bin/docker-entrypoint.sh
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:pet_gateway.localhost"
    - "traefik.docker.network=pet_host"
    depends_on:
    - traefik

  pet_porta:
    build: "./pet_porta/"
    container_name: pet_porta
    depends_on:
    - pet_gateway
    volumes:
    - ./pet_porta/src:/usr/src/pet_porta/src
    expose:
      - ${PET_APP_PORT}
    environment:
      PET_APP_PORT: ${PET_APP_PORT}
    ports:
      - ${PET_APP_PORT}:${PET_APP_PORT}
    labels:
    - "traefik.enabled=true"
    - "traefik.frontend.rule=Host:pet_porta.localhost" 
    - "traefik.docker.network=pet_host"
    networks:
    - pet_host
    entrypoint:
    - /usr/local/bin/docker-entrypoint.sh
    depends_on:
    - traefik

networks:
  pet_host:
    external: true
  internal:
    external: true
volumes:
  portainerdata:
  db:
