version: '3.7'
services:
  traefik:
    image: traefik:latest # The official Traefik docker image
    container_name: traefik
    command: --docker --api --docker.watch --docker.domain=docker.localhost --logLevel=DEBUG  --docker.endpoint=tcp://socat:2375 --docker.exposedbydefault=false # Enables the web UI and tells Træfik to listen to docker, without exposing by default
    networks:
    - pet_host
    ports:
    - "80:80"     # The HTTP port
    - "8080:8080" # The Web UI (enabled by --api)
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    - /root/traefik.toml:/traefik.toml
    - /root/acme.json:/acme.json

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
    - '9000:9000'
    networks: 
    - pet_host
    labels:
    - "traefik.enable=false"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainerdata:/data


  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    volumes:
    - .pet_database:/usr/src/pet_database
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=pet_host"
    environment:
      MYSQL_DATABASE: pet_db
    networks:
    - pet_host
    ports:
    - 3005:3005

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:80
    depends_on:
    - mysql
    networks:
    - pet_host

  socat:
    image: alpine/socat
    container_name: socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - pet_host
    depends_on:
    - traefik

  pet_database:
    build: "./pet_database/"
    container_name: pet_database
    volumes:
    - .pet_database:/usr/src/pet_database
    environment:
    - DB_HOST=db
    - DB_USER=root
    - DB_NAME=${MYSQL_DATABASE}
    - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    labels:
    - traefik.enable=true"
    - "traefik.docker.network=pet_host.localhost"
    networks:
    - pet_host

  pet_gateway:
    build: "./pet_gateway/"
    container_name: pet_gateway
    command: -t -i --device=/dev/bus/usb/003/017 ubuntu bash
    environment:
    - API_HOST=${API_HOST}
    - API_SERVER_PORT=${API_SERVER_PORT}
    ports:
    - "3000:3000"
    networks:
    - pet_host
    volumes:
    - ./server/src:/usr/src/pet_gateway/src
    - db:/usr/src/pet_gateway
    entrypoint:
    - /usr/local/bin/docker-entrypoint.sh
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:pet_gateway.localhost"
    - "traefik.docker.network=pet_host"
    depends_on:
    - mysql
    - traefik

  pet_porta:
    build: "./pet_porta/"
    container_name: pet_porta
    depends_on:
    - pet_gateway
    volumes:
    - ./pet_porta/src:/usr/src/pet_porta/src
    ports:
    - "8000:8000"
    labels:
    - "traefik.enabled=true"
    - "traefik.frontend.rule=Host:pet_porta.localhost" 
    - "traefik.docker.network=pet_host"
    networks:
    - pet_host
    entrypoint:
    - /usr/local/bin/docker-entrypoint.sh
    depends_on:
    - pet_gateway
    - traefik

networks:
  pet_host:
    external: true
volumes:
  portainerdata:
  db:
