version: "3.7"
services:
  # controlador dos containers
  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: portainer
    ports:
    - "9000:9000"
    networks:
    - backend
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainerdata:/data

  # teste com novo banco de dados
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    command: --smallfiles
    volumes:
    - pet:/data
    networks:
    - backend

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-board
    restart: always
    ports:
    - "8081:8080"
    networks:
    - backend
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
    - mongo

  # microserviço que oferece o front-end e solicita/envia requisições/respostas ao cliente
  pet_porta:
    build: "./pet_porta/"
    container_name: pet_porta
    restart: always
    ports:
      - "3020:3000"
    networks:
      frontend:
      backend:
        ipv4_address: 172.20.0.20
        ipv6_address: 2001:3984:3989::20
    entrypoint:
      - /usr/local/bin/docker-entrypoint.sh
    depends_on:
      - pet_gateway

  # microserviço para tratar todas as requisiçoes
  pet_gateway:
    build: "./pet_gateway/"
    container_name: pet_gateway
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
        ipv6_address: 2001:3984:3989::5
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mongo-express

  # microserviço para ativar o arduino
  pet_arduino:
    build: "./pet_arduino/"
    container_name: pet_arduino
    ports:
    - "3003:3000"
    privileged: true
    devices:
    - /dev:/dev
    #command: -t -i --device=/dev/bus/usb/003/017 ubuntu bash
    entrypoint:
    - /usr/local/bin/docker-entrypoint.sh
    networks:
      backend:
        ipv4_address: 172.20.0.7
        ipv6_address: 2001:3984:3989::7

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
      - subnet: 2001:3984:3989::/64
  frontend:
    external: true
volumes:
  portainerdata:
  pet: