version: '3.3'
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
    - '9000:9000'
    networks:
    - internal
    labels:
    - "traefik.enable=false"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainerdata:/data

  traefik:
    image: traefik # The official Traefik docker image
    command: --api --docker.exposedbydefault=false # Enables the web UI and tells Træfik to listen to docker, without exposing by default
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    depends_on:
    - pet-gateway
    - pet-porta
      
  pet-gateway:
    build: "./pet_gateway/"
    container_name: pet_gateway
    networks:
    - internal
    - pet_host
    volumes:
    - db:/usr/src/gateway
    entrypoint:
    - /usr/local/bin/docker-entrypoint.sh
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:${APP_HOST}"

  pet-porta:
    build: "./pet_porta/"
    container_name: pet_porta
    depends_on:
    - pet-gateway
    labels:
    - "traefik.enabled=true"
    - "traefik.frontend.rule=Host:${APP_HOST}" 
    networks:
    - internal
    - pet_host
    entrypoint:
    - /usr/local/bin/docker-entrypoint.sh

networks:
  pet_host:
    external: true
  internal:
    external: false
volumes:
  portainerdata:
  db:
