[entryPoints]
  [entryPoints.http]
  address = ":8080"

[frontends]

  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host: pet_porta.localhost"

  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend2.routes.test_1]
    rule = "Host: pet_gateway.localhost"

[backends]
  [backends.backend1]
    [backends.backend1.LoadBalancer]
      method = "drr"

    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:8000"
    weight = 1

  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://127.0.0.1:3000"
    weight = 2