[entryPoints]
  [entryPoints.http]
  address = ":8081"

[frontends]

  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host: localhost:3001"

[backends]
  [backends.backend1]
    [backends.backend1.LoadBalancer]
      method = "drr"

    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:3000"
    weight = 1
